---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kwebs-patroni-postgres-operator
    pod-security.kubernetes.io/enforce: restricted
  name: operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    control-plane: kwebs-patroni-postgres-operator
spec:
  selector:
    matchLabels:
      control-plane: kwebs-patroni-postgres-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kwebs-patroni-postgres-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - args:
            - --leader-elect
          image: ghcr.io/k-web-s/patroni-postgres-operator
          name: manager
          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: requests.memory
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 24Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
