#!/bin/sh

set -e

test -n "${PRIMARY_ADDRESS}"

PGDATA=/var/lib/postgresql/data
PGDATAOLD=${PGDATA}.old

PRESERVE_FILES="postgresql.conf postgresql.base.conf postgresql.auto.conf pg_hba.conf pg_ident.conf"

while ! nc -w1 -z ${PRIMARY_ADDRESS} 5873 < /dev/null >/dev/null; do
    echo "[-] Waiting for rsync daemon to start"
    sleep 1
done

echo "[+] rsync daemon came up"

mkdir -p "${PGDATAOLD}"
for f in ${PRESERVE_FILES}; do
    if [ -f "${PGDATA}/${f}" ]; then
        if [ ! -f "${PGDATAOLD}/${f}" ]; then
            cp "${PGDATA}/${f}" "${PGDATAOLD}/${f}"
        fi
    fi
done

rsync -avH --delete rsync://${PRIMARY_ADDRESS}:5873/postgresql-data/ ${PGDATA}/

for f in ${PRESERVE_FILES}; do
    if [ -f "${PGDATAOLD}/${f}" ]; then
        cp "${PGDATAOLD}/${f}" "${PGDATA}/${f}"
    fi
done

rm -rf "${PGDATAOLD}"
