---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kwebs-patroni-postgres-operator-leader-election-rolebinding
  namespace: kwebs-patroni-postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kwebs-patroni-postgres-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: kwebs-patroni-postgres-operator
    namespace: kwebs-patroni-postgres-operator
